function _initcache_help
    # Show top-level help if no args, or "help" with no further args
    if test (count $argv) -eq 0
        _initcache_echo_preset header -n "Usage: "
        _initcache_echo_preset command "initcache <command> [<target>] [<args>...]"
        echo ""
        echo "Initialize, cache, and manage shell init snippets generated by external commands."
        echo ""
        _initcache_echo_preset header "Available commands:"
        _initcache_echo_preset command -n "  source   "
        echo "Cache and source command output for a target"
        _initcache_echo_preset command -n "  clear    "
        echo "Clear cached entries"
        _initcache_echo_preset command -n "  list     "
        echo "List cached entries"
        _initcache_echo_preset command -n "  update   "
        echo "Refresh cache for a target"
        _initcache_echo_preset command -n "  help     "
        echo "Show help for a command"
        echo ""
        _initcache_echo_preset info "Run 'initcache help <command>' for details and examples (e.g., 'initcache help source')."
        return 0
    end

    set -f subcommand $argv[1]

    switch $subcommand
        case source
            _initcache_echo_preset header -n "Usage: "
            _initcache_echo_preset command "initcache source <target> <args>..."
            echo ""
            echo "Cache and source the output of the given command."
            echo "The first word is treated as the target key; the remaining words are passed as args."
            echo ""
            _initcache_echo_preset header "Examples:"
            _initcache_echo_preset command -n "  initcache source zoxide init fish"
            echo "  Cache and source the output of 'zoxide init fish'"
        case clear
            _initcache_echo_preset header -n "Usage: "
            _initcache_echo_preset command "initcache clear [<target> ...]"
            echo ""
            echo "Clear cached entries. With no target, all caches are cleared."
            echo ""
            _initcache_echo_preset header "Examples:"
            _initcache_echo_preset command -n "  initcache clear"
            echo "               Clear all caches"
            _initcache_echo_preset command -n "  initcache clear zoxide"
            echo "        Clear only 'zoxide' cache"
        case list
            _initcache_echo_preset header -n "Usage: "
            _initcache_echo_preset command "initcache list"
            echo ""
            echo "List all cached entries."
        case update
            _initcache_echo_preset header -n "Usage: "
            _initcache_echo_preset command "initcache update <target> <args>..."
            echo ""
            echo "Refresh the cache for the specified command."
            echo ""
            _initcache_echo_preset header "Examples:"
            _initcache_echo_preset command -n "  initcache update zoxide init fish"
            echo "  Refresh cache for 'zoxide init fish'"
        case '*'
            _initcache_echo_preset error \
                "unknown subcommand '$subcommand'" \
                "Try 'initcache help' for usage."
            return 1
    end
end
